name: flask-ctapipe-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - flask
  - plotly
  - pandas
  - pyyaml
  - plotly
  - matplotlib
  - requests
  - numpy
  - plotly
  - nodejs
  - pip
  - pip:
    - ctapipe